set(GLFW_LIB_NAME "glfw")
set(GLFW_INCLUDE_PATH "${CMAKE_CURRENT_LIST_DIR}/${GLFW_LIB_NAME}/include")

set(GLFW_BUILD_EXAMPLES OFF CACHE INTERNAL "" FORCE)
set(GLFW_BUILD_TESTS	OFF CACHE INTERNAL "" FORCE)
set(GLFW_BUILD_DOCS		OFF CACHE INTERNAL "" FORCE)
set(GLFW_INSTALL 		OFF CACHE INTERNAL "" FORCE)
add_subdirectory("${GLFW_LIB_NAME}")

set_target_properties("${GLFW_LIB_NAME}" PROPERTIES FOLDER "${LIB_DIR}")